######################################################
##  API Server | Deployment
######################################################   
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-server
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
  labels:
    app: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: {{ .Values.image.repository }}
        ports:
          - containerPort: 3000
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
          - name: APP_NAME
            value : FormIo
          - name: NODE_ENV
            value : {{ .Values.appEnv }}
          - name: PRIMARY
            value : "true"
          - name: PORT
            value : {{ .Values.port | quote }}
          - name: PORTAL_ENABLED
            value: {{ .Values.portalEnabled | quote }}
          - name: MONGO
            value: {{ .Values.mongo }}
          - name: ADMIN_EMAIL
            value: {{ .Values.adminEmail }}
          - name: ADMIN_PASS
            value: {{ .Values.adminPass }}
          - name: DB_SECRET
            value: {{ .Values.dbSecret }}
          - name: JWT_SECRET
            value: {{ .Values.jwtSecret }}
          - name: LICENSE_KEY
            value: {{ .Values.licenseKey }}
          - name: PDF_SERVER
            value: {{ .Values.pdfServer }}
          - name: BASE_URL
            value: {{ .Values.baseUrl }}
          - name: DEBUG
            value: {{ .Values.debug | quote }}

---
######################################################
##  Nginx | Deployment
###################################################### 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: default.conf
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
     
---
######################################################
##  PDF Server | Deployment
######################################################     
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pdf-server
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
  labels:
    app: pdf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-server
  template:
    metadata:
      labels:
        app: pdf-server
    spec:
      containers:
      - name: pdf-server
        image: {{ .Values.pdf.repository }}
        ports:
          - containerPort: 4005
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
          - name: FORMIO_PDF_PORT
            value: "4005"
          - name: MONGO
            value: {{ .Values.mongo }}
          - name: FORMIO_S3_KEY
            value: {{ .Values.formioS3Key }}
          - name: FORMIO_S3_SECRET
            value: {{ .Values.formioS3Secret }}
          - name: FORMIO_S3_BUCKET
            value: {{ .Values.formioS3Bucket }}
          - name: FORMIO_S3_REGION
            value: us-east-2
          - name: LICENSE_KEY
            value: {{ .Values.licenseKey }}
          - name: DEBUG
            value: {{ .Values.debug | quote }}